import styles from "../styles/Home.module.css";
import Head from "next/head";
<Head>
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" />
</Head>;
export default function Home() {
  return (
    <div className={styles.Board}>
      <div className={styles.rows}>
        <div className={styles.columns1}>Tripple Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns2}>Double Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns1}>Tripple Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns2}>Double Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns1}>Tripple Word Score</div>
      </div>
      <div className={styles.rows}>
        <div className={styles.columns}></div>
        <div className={styles.columns3}>Double Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns3}>Double Word Score</div>
        <div className={styles.columns}></div>
      </div>
      <div className={styles.rows}>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns3}>Double Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns3}>Double Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
      </div>
      <div className={styles.rows}>
        <div className={styles.columns2}>Double Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns3}>Double Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns3}>Double Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns2}>Double Letter Score</div>
      </div>
      <div className={styles.rows}>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns3}>Double Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns3}>Double Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
      </div>
      <div className={styles.rows}>
        <div className={styles.columns}></div>
        <div className={styles.columns4}>Tripple Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns4}>Tripple Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns4}>Tripple Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns4}>Tripple Letter Score</div>
        <div className={styles.columns}></div>
      </div>
      <div className={styles.rows}>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns2}>Double Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns2}>Double Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns2}>Double Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns2}>Double Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
      </div>
      <div className={styles.rows}>
        <div className={styles.columns1}>Tripple Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns2}>Double Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns5}>&#9733;</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns2}>Double Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns1}>Tripple Word Score</div>
      </div>
      <div className={styles.rows}>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns2}>Double Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns2}>Double Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns2}>Double Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns2}>Double Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
      </div>
      <div className={styles.rows}>
        <div className={styles.columns}></div>
        <div className={styles.columns4}>Tripple Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns4}>Tripple Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns4}>Tripple Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns4}>Tripple Letter Score</div>
        <div className={styles.columns}></div>
      </div>
      <div className={styles.rows}>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns3}>Double Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns3}>Double Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
      </div>
      <div className={styles.rows}>
        <div className={styles.columns2}>Double Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns3}>Double Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns3}>Double Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns2}>Double Letter Score</div>
      </div>
      <div className={styles.rows}>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns3}>Double Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns3}>Double Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
      </div>
      <div className={styles.rows}>
        <div className={styles.columns}></div>
        <div className={styles.columns3}>Double Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns3}>Double Word Score</div>
        <div className={styles.columns}></div>
      </div>
      <div className={styles.rows}>
        <div className={styles.columns1}>Tripple Word Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns2}>Double Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns2}>Double Letter Score</div>
        <div className={styles.columns}></div>
        <div className={styles.columns}></div>
        <div className={styles.columns1}>Tripple Word Score</div>
      </div>
    </div>
  );
}
